version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-app
    restart: always
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - budget
    depends_on:
      - mysql
      - redis
      - mailhog

  mysql:
    image: mysql:8.0
    container_name: budget-mysql
    restart: always
    environment:
      MYSQL_DATABASE: budget
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: budget
      MYSQL_PASSWORD: budget
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - budget

  redis:
    image: redis:alpine
    container_name: budget-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - budget

  mailhog:
    image: mailhog/mailhog
    container_name: budget-mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - budget

  nginx:
    image: nginx:alpine
    container_name: budget-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - budget

networks:
  budget:

volumes:
  db_data:
